[toolchain]
package_manager = "yarn"

[workspace]
members = ["programs/ft-solana"]

[features]
resolution = true
skip-lint = false

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"


[programs.localnet]
ft_solana = "FNufCrMUFRhAGRYHNbq7r8YPy8cbjc6hJvsKUFD7Qhuh" 

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
